name: auto-release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight (00:00) UTC every day
  push:
    branches:
      - main

jobs:
  check_and_build_new_xanmod_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last release tags
        id: get_latest_release_tags
        uses: actions/github-script@v7
        with:
          script: |
            const myLatestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("my_latest_tag", myLatestRelease.data.tag_name);
            
            const xmLatestRelease = await github.rest.repos.getLatestRelease({
              owner: 'xanmod',
              repo: 'linux',
            });
            core.setOutput("xanmod_latest_tag", xmLatestRelease.data.tag_name);
      
      - name: Build
        id: build_kernel
        run: |
          MY_LATEST_TAG=${{ steps.get_latest_release_tags.outputs.my_latest_tag }}
          XANMOD_LATEST_TAG=${{ steps.get_latest_release_tags.outputs.xanmod_latest_tag }}
          
          if [[ "${MY_LATEST_TAG}" == "${XANMOD_LATEST_TAG}" ]]; then
            echo "Current xanmod release version ${MY_LATEST_TAG} is same as version of last my build ${MY_LATEST_TAG}. No need to build."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            sudo bash auto-build.sh "$XANMOD_LATEST_TAG"
          fi
      
      - name: Release
        if: ${{ (steps.build_kernel.outcome == 'success') && (steps.build_kernel.outputs.skip != 'true') }}
        uses: softprops/action-gh-release@v2.0.6 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          append_body: false
          fail_on_unmatched_files: true
          name: "Version ${{ steps.get_latest_release_tags.outputs.xanmod_latest_tag }}"
          tag_name: "${{ steps.get_latest_release_tags.outputs.xanmod_latest_tag }}"
          files: |
            linux-${{ steps.get_latest_release_tags.outputs.xanmod_latest_tag }}-kernel/debs/*
