name: auto-release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs at midnight (00:00) UTC every day
  push:
    branches:
      - main

jobs:
  check_and_build_new_xanmod_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last release tags
        id: get_latest_release_tags
        uses: actions/github-script@v7
        with:
          script: |
            const myLatestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("my_latest_tag", myLatestRelease.data.tag_name);
      
      - name: setup deb822 repos
        run: |
          if [[ $ImageOS == "ubuntu24" ]]; then
            cat <<EOF > deb822sources
          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://security.ubuntu.com/ubuntu/
          Suites: noble-security
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble-updates
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
          Suites: noble
          Components: main restricted multiverse universe
          Architectures: arm64

          Types: deb
          URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
          Suites: noble-updates
          Components: main restricted multiverse universe
          Architectures: arm64
          EOF

            sudo mv deb822sources /etc/apt/sources.list.d/ubuntu.sources
          else
            cat <<EOF > sources.list
          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://security.ubuntu.com/ubuntu/
          Suites: noble-security 
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu/
          Suites: noble-updates
          Components: main restricted universe
          Architectures: amd64

          Types: deb
          URIs: http://ports.ubuntu.com/ubuntu-ports/
          Suites: noble
          Components: main restricted multiverse universe
          Architectures: arm64

          Types: deb
          URIs: http://ports.ubuntu.com/ubuntu-ports/
          Suites: noble-updates
          Components: main restricted multiverse universe
          Architectures: arm64
          EOF
            sudo mv sources.list /etc/apt/sources.list
          fi
      
      - name: Build
        id: build_kernel
        run: |
          MY_LATEST_TAG=${{ steps.get_latest_release_tags.outputs.my_latest_tag }}
          
          sudo apt install jq
          XANMOD_LATEST_TAG=$(curl -s https://gitlab.com/api/v4/projects/51590166/releases/ | jq '.[]' | jq -r '.name' | head -1)
          echo "xanmod_build_tag=${XANMOD_LATEST_TAG}" >> "$GITHUB_OUTPUT"
          
          if [[ ${XANMOD_LATEST_TAG} == *"-rt-xanmod1" ]]; then
            echo "Skipping rt version ${XANMOD_LATEST_TAG}. No need to build."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            myversion="$(echo "${MY_LATEST_TAG}" | cut -d. -f1)"
            newversion="$(echo "${XANMOD_LATEST_TAG}" | cut -d. -f1)"
            
            if [ "${myversion}" -eq "${newversion}" ]; then
              myversion="$(echo "${MY_LATEST_TAG}" | cut -d. -f2)"
              newversion="$(echo "${XANMOD_LATEST_TAG}" | cut -d. -f2)"
            fi
            
            if [ "${myversion}" -ge "${newversion}" ]; then
              echo "Current xanmod release version: ${MY_LATEST_TAG}; my latest build: ${MY_LATEST_TAG}. No need to build."
              echo "skip=true" >> "$GITHUB_OUTPUT"
            else
              sudo bash auto-build.sh "$XANMOD_LATEST_TAG"
            fi
          fi
          
      
      - name: Release
        if: ${{ (steps.build_kernel.outcome == 'success') && (steps.build_kernel.outputs.skip != 'true') }}
        uses: softprops/action-gh-release@v2.0.6 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          append_body: false
          fail_on_unmatched_files: true
          name: "Version ${{ steps.build_kernel.outputs.xanmod_build_tag }}"
          tag_name: "${{ steps.build_kernel.outputs.xanmod_build_tag }}"
          files: |
            linux-${{ steps.build_kernel.outputs.xanmod_build_tag }}-kernel/debs/*
