name: test

on:
  push:
    branches:
      - main
 
  workflow_dispatch:

jobs:
  get-latest-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: get_latest_release_tag
        uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("tag_name", latestRelease.data.tag_name);

      - name: Assign latest release tag to variable and echo
        run: |
          LATEST_TAG=${{ steps.get_latest_release_tag.outputs.tag_name }}
          echo "The latest release tag is $LATEST_TAG"
