name: test

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get latest release tag
        id: get_latest_release_tag
        uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("tag_name", latestRelease.data.tag_name);
      
      - name: Build
        run: |
          RELEASE_VERSION=${{ steps.get_latest_release_tag.outputs.tag_name }}"
          echo "$RELEASE_VERSION"
